-- Page list

CREATE TABLE PAGE (
	PAGE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,		-- Page Identification
    PAGE_NAME VARCHAR(150) NOT NULL							-- Page Name
);

INSERT INTO PAGE (PAGE_NAME) VALUES ('home');
INSERT INTO PAGE (PAGE_NAME) VALUES ('our-team');
INSERT INTO PAGE (PAGE_NAME) VALUES ('services');
INSERT INTO PAGE (PAGE_NAME) VALUES ('contact');